- hosts: windows10
  gather_facts: no
  vars:
    ansible_user: "{{ var_username }}"
    ansible_password: "{{ var_password }}"
    ansible_winrm_operation_timeout_sec: 900
    ansible_winrm_read_timeout_sec: 1000
  tasks:
  - name: Start Script
    ansible.windows.win_shell: C:\Repos\Exchange\ExchangeOnline.ps1
