---
- hosts: windows10
  gather_facts: no
  vars:
    #ansible_user: "{{ ansible_user }}"
    #ansible_password: "{{ ansible_password }}"
    ansible_connection: ssh
    ansible_shell_type: cmd
    #ansible_connection: winrm
    #ansible_winrm_transport: basic
    #ansible_port: 5985
    #ansible_winrm_operation_timeout_sec: 900
    #ansible_winrm_read_timeout_sec: 1000
  tasks:
    - debug: 
        msg: test
    - name: Run remote PowerShell Script
      win_command: powershell.exe -ExecutionPolicy ByPass -File C:\Repos\Exchange\PowerShellService\PowerShellService\PowerShellService\ExchangeOnline.ps1
